# Generated by Django 3.1.7 on 2021-07-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funApp', '0003_auto_20210710_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='passengers',
        ),
        migrations.AddField(
            model_name='flight',
            name='passengers',
            field=models.ManyToManyField(null=True, to='funApp.Passenger'),
        ),
    ]
